### ISSUE TITLE
Incorrect nsfw detection

### ISSUE THREAD

**Issue by YunoGasai67** [d00ML0rDz/NsfwSpy#4]
Apparently it detects YouTube links as nsfw? And pretty much any imgur or tenor link

**Comment by d00ML0rDz** [comment]
Do you have some examples of the URLs you're finding this on? The URLs need to direct to an image file so that may be the issue here.

**Comment by YunoGasai67** [comment]
Well for example the attachment below it sees as hentai

**Comment by YunoGasai67** [comment]
Oops it didn't sent the attachment one sec

**Comment by YunoGasai67** [comment]
![avatars-fo4Vr0Le0ku0izIJ-uv5qbA-t500x500](https://user-images.githubusercontent.com/59923820/141687087-67985720-e7a8-4fb3-9532-f7b8ef217e1c.jpg)

**Comment by d00ML0rDz** [comment]
Unfortunately, NsfwSpy isn't perfect. We usually only see approximately a 3% chance of a neutral image image being identified as NSFW, and this looks to be one of those cases. 

As you can see though, from the score below it isn't very confident it's hentai.

![image](https://user-images.githubusercontent.com/66832778/141687315-3e1daa45-2bc1-44bc-b343-268bd8f15743.png)

I'll add this image to our neutral dataset so that we can train on it in the future.

**Comment by YunoGasai67** [comment]
Cool, thanks!
